(defvar emacs-dir "~/.emacs.d")
(load-file (concat emacs-dir "/global.el"))
(load-dir (concat emacs-dir "/packages"))
(load-dir (concat emacs-dir "/loads"))
(load-file (concat emacs-dir "/key-binding.el"))
