
(define-key global-map "\C-o" 'other-window)
(define-key global-map "\C-c\C-v" 'split-window-vertically)
(define-key global-map "\C-c\C-h" 'split-window-horizontally)
(define-key global-map "\C-c\C-d" 'delete-other-windows)
(define-key global-map "\C-c\C-t" 'indenet-all)
(define-key global-map "\C-j" 'fastdown)
(define-key global-map "\C-h" 'fastup)
(define-key global-map "\C-l" 'next-buffer)
(define-key global-map "\M-l" 'previous-buffer)
(define-key global-map "\C-c\C-q" (lambda () (interactive) (kill-buffer nil)))
(define-key global-map "\C-c\C-l" (lambda () (interactive) (shell "/bin/bash") (rename-uniquely)))
(define-key global-map "\C-c\C-r" 'query-replace)
(define-key global-map "\C-c\C-o" 'comment-region)
(define-key global-map "\C-c\C-p" 'uncomment-region)
(define-key global-map "\C-v" 'undo)
(define-key global-map "\M-v" 'redo)
(define-key global-map "\C-w" 'kill-region)
(define-key global-map "\C-y" 'yank)
