
;;ruby-mode
(add-hook 'ruby-mode-hook
	  '(lambda ()
	     (setq ruby-insert-encoding-magic-comment nil)
	     ;;	     (define-key ruby-mode-map "\C-h" 'backward-kill-word)
	     (define-key global-map "\C-c\C-r" 'query-replace)
	     (define-key ruby-mode-map "\C-m" 'newline-and-indent)
	     ;;	     (define-key ruby-mode-map "\C-x\C-s" (lambda () (interactive) (command-execute 'indent-all) (command-execute 'save-buffer)))
	     (define-key ruby-mode-map "\C-c\C-e" 'indent-all)
	     (define-key ruby-mode-map "\C-o" 'other-window)
	     (define-key ruby-mode-map "\C-j" 'fastdown)
	     (define-key ruby-mode-map "\C-h" 'fastup)
	     (define-key ruby-mode-map "\C-l" 'next-buffer)
	     (define-key ruby-mode-map "\M-l" 'previous-buffer)))
(add-to-list 'auto-mode-alist '("\\.rake$" . ruby-mode))
(add-to-list 'auto-mode-alist '("Rakefile$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.gemspec$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.ru$" . ruby-mode))
(add-to-list 'auto-mode-alist '("Gemfile$" . ruby-mode))
(add-to-list 'auto-mode-alist '("Guardfile$" . ruby-mode))
